spring.application.name=OnlyBuns
spring.datasource.url=jdbc:postgresql://localhost:5432/onlybuns
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
image.upload-dir=images/originals
image.compressed-dir=images/compressed
spring.task.scheduling.pool.size=2
spring.cache.type=simple
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.cache.redis.time-to-live=600000

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.template.default-destination=location-queue
spring.jms.listener.auto-startup=true


# Postavke za email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nik.letvencuk@gmail.com
spring.mail.password=onps pbcw umuk xobg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.profiles.active=onlybuns
spring.main.allow-bean-definition-overriding=true

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

